version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run:  npm --version
  test:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run:  npm --version
  analyze:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run:  npm --version
workflows:
  sdlc:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
