version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      -run: npm run lint
  test:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      -run: npm run test
  analyze:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      -run: npm audit
workflows:
  sdlc:
    jobs:
      - build
      - test
      - analyze
